-- Create a table for admin emails
CREATE TABLE IF NOT EXISTS admin_whitelist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE admin_whitelist ENABLE ROW LEVEL SECURITY;

-- Create a secure function to check if an email is an admin
-- This avoids exposing the entire list of admin emails via a SELECT policy
CREATE OR REPLACE FUNCTION check_is_admin(email_input TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (SELECT 1 FROM admin_whitelist WHERE email = email_input);
END;
$$;

-- Grant execute permission to anon and authenticated roles
GRANT EXECUTE ON FUNCTION check_is_admin TO anon, authenticated;

-- Example insertion (You can add your admin email here)
-- INSERT INTO admin_whitelist (email) VALUES ('your_email@example.com');
