-- Dashboard-related tables/functions (profile views, interests, suggestions)

-- 1) Track profile views (who viewed whom)
create table if not exists profile_views (
  id bigint generated by default as identity primary key,
  viewer_id uuid references profiles(id) on delete cascade not null,
  viewed_id uuid references profiles(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists profile_views_viewed_created_at_idx
  on profile_views (viewed_id, created_at desc);

create index if not exists profile_views_viewer_created_at_idx
  on profile_views (viewer_id, created_at desc);

alter table profile_views enable row level security;

drop policy if exists "Users can insert their own profile views" on profile_views;
drop policy if exists "Users can view who viewed them" on profile_views;

create policy "Users can insert their own profile views" on profile_views
  for insert
  with check (auth.uid() = viewer_id);

create policy "Users can view who viewed them" on profile_views
  for select
  using (auth.uid() = viewed_id);


-- 2) Track interests (requests) between users
create table if not exists interests (
  id bigint generated by default as identity primary key,
  from_user uuid references profiles(id) on delete cascade not null,
  to_user uuid references profiles(id) on delete cascade not null,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  responded_at timestamp with time zone
);

create unique index if not exists interests_from_to_unique
  on interests (from_user, to_user);

create index if not exists interests_to_status_created_at_idx
  on interests (to_user, status, created_at desc);

create index if not exists interests_from_status_created_at_idx
  on interests (from_user, status, created_at desc);

alter table interests enable row level security;

drop policy if exists "Users can create interests from themselves" on interests;
drop policy if exists "Users can view their interests" on interests;
drop policy if exists "Users can respond to interests sent to them" on interests;

create policy "Users can create interests from themselves" on interests
  for insert
  with check (auth.uid() = from_user);

create policy "Users can view their interests" on interests
  for select
  using (auth.uid() = from_user or auth.uid() = to_user);

create policy "Users can respond to interests sent to them" on interests
  for update
  using (auth.uid() = to_user)
  with check (auth.uid() = to_user);


-- 3) RPC: suggested matches for the logged-in user
-- Returns a small set of profiles with a simple compatibility score.
create or replace function get_match_suggestions(limit_input int default 3)
returns table (
  id uuid,
  first_name text,
  last_name text,
  age int,
  city text,
  profession text,
  photo text,
  compatibility int,
  verified boolean
)
language sql
stable
as $$
  with me as (
    select *
    from profiles
    where id = auth.uid()
  ),
  candidates as (
    select
      p.*,
      -- common interests count (0 if either side is null)
      coalesce(
        cardinality(
          array(
            select unnest(coalesce(p.interests, '{}'::text[]))
            intersect
            select unnest(coalesce(me.interests, '{}'::text[]))
          )
        ),
        0
      ) as common_interests,
      (case when me.preferred_city is not null and p.city = me.preferred_city then 1 else 0 end) as preferred_city_match,
      (case when me.looking_for is not null and p.gender = me.looking_for then 1 else 0 end) as gender_match
    from profiles p
    cross join me
    where p.id <> auth.uid()
  )
  select
    c.id,
    c.first_name,
    c.last_name,
    -- age derived from date_of_birth (null-safe)
    (case
      when c.date_of_birth is null then null
      else date_part('year', age(c.date_of_birth))::int
    end) as age,
    c.city,
    c.profession,
    c.photos[1] as photo,
    least(
      99,
      60
      + (c.common_interests * 8)
      + (c.preferred_city_match * 12)
      + (c.gender_match * 10)
    ) as compatibility,
    coalesce(c.is_complete, false) as verified
  from candidates c
  order by compatibility desc nulls last, random()
  limit greatest(1, limit_input);
$$;

